spring:
  application:
    name: reva-pathah
  datasource:
    url: jdbc:mysql://localhost:3306/preparation_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  flyway:
    enabled: true
 